- name: Install Cassandra on a Node
  hosts:
    - cassandra_seed
  vars:
    ansible_ssh_user: root
  roles:
    - role: cassandra
      vars:
        deploy_env: dev
        project: openmeet
        type: cassandra
        region: sfo3
        domain_name: scanlanservices.com
        wipe_data: True
        keystore_password: butterballsandwitch32
        truststore_password: butterballsandwitch32
        stores_dir: /etc/cassandra/stores