---
- name: Configure Cassandra with Let's Encrypt SSL Certificates
  hosts: cassandra
  vars:
    keystore_password: butterball
    truststore_password: butterball
    stores_dir: /etc/cassandra/stores
  tasks:
    - name: Create stores directory
      file:
        path: "{{ stores_dir }}"
        state: directory
        mode: '0700'
        owner: cassandra
        group: cassandra

    - name: Convert Let's Encrypt certificates to PKCS12
      community.crypto.openssl_pkcs12:
        action: export
        path: "{{ stores_dir }}/node-keystore.p12"
        friendly_name: "{{ inventory_hostname}}.{{domain_name}}"
        privatekey_path: "/etc/letsencrypt/live/{{ inventory_hostname }}.{{ domain_name }}/privkey.pem"
        certificate_path: "/etc/letsencrypt/live/{{ inventory_hostname }}.{{ domain_name }}/fullchain.pem"
        passphrase: "{{ keystore_password }}"
        state: present
        passphrase: "{{ keystore_password }}"

    - name: Create keystore from PKCS12
      community.general.java_cert:
        pkcs12_path: "{{ stores_dir }}/node-keystore.p12"
        pkcs12_password: "{{ keystore_password }}"
        pkcs12_alias: "{{ inventory_hostname }}.{{ domain_name }}"
        cert_alias: "{{ inventory_hostname }}.{{ domain_name }}"
        keystore_path: "{{ stores_dir }}/node-keystore.jks"
        keystore_pass: "{{ keystore_password }}"
        keystore_create: true
        keystore_type: "JKS"
        state: present

    - name: Create truststore with Let's Encrypt root certificate
      community.general.java_cert:
        cert_path: "/etc/letsencrypt/live/{{ inventory_hostname }}.{{ domain_name }}/chain.pem"
        keystore_path: "{{ stores_dir }}/node-truststore.jks"
        keystore_pass: "{{ truststore_password }}"
        cert_alias: CARoot
        keystore_create: true
        state: present

    - name: Set proper permissions on store files
      file:
        path: "{{ item }}"
        owner: cassandra
        group: cassandra
        mode: '0600'
      loop:
        - "{{ stores_dir }}/node-keystore.p12"
        - "{{ stores_dir }}/node-keystore.jks"
        - "{{ stores_dir }}/node-truststore.jks"

    - name: Restart Cassandra service
      systemd:
        name: cassandra
        state: restarted